<?php
/*************************************************************************************
 * Pawn For Geshi 1.0
 * -----
 * Author: Jan Schütze (JanS@DracoBlue.de)
 * Copyright: (c) 2004 Nigel McNie (http://qbnz.com/highlighter/)
 * Release Version: 1.0
 * Date Started: 2007/07/01
 * Last Modified: $Date: 2006/07/01 22:19:00 $
 *
 * Pawn language file for GeSHi with additions for sa-mp
 *
 * CHANGES
 * -------
 * 2007/07/01 (1.0.0)
 *   -  First Release
 *
 *************************************************************************************
 *
 *   Pawn for Geshi is released under the terms of MIT License.
 *   Copyright 2007 by DracoBlue (http://dracoblue.net)
 *
 ************************************************************************************/

$language_data = array (
    'LANG_NAME' => 'pawn',
    'COMMENT_SINGLE' => array(1 => '//', 2 => '#'),
    'COMMENT_MULTI' => array('/*' => '*/'),
    'CASE_KEYWORDS' => GESHI_CAPS_NO_CHANGE,
    'QUOTEMARKS' => array("'", '"'),
    'ESCAPE_CHAR' => '\\',
    'KEYWORDS' => array(
        1 => array(
            'if', 'return', 'while', 'case', 'continue', 'default',
            'do', 'else', 'for', 'switch', 'goto'
            ),
        2 => array(
            'null', 'false', 'break', 'true', 'function', 'enum', 'extern', 'inline'
            ),
        3 => array(
            'AddPlayerClass',
            'AddPlayerClassEx',
            'AddStaticPickup',
            'AddStaticVehicle',
            'AddStaticVehicleEx',
            'AddVehicleComponent',
            'AllowAdminTeleport',
            'AllowInteriorWeapons',
            'AllowPlayerTeleport',
            'ApplyAnimation',
            'Attach3DTextLabelToPlayer',
            'Attach3DTextLabelToVehicle',
            'AttachObjectToPlayer',
            'AttachPlayerObjectToPlayer',
            'AttachTrailerToVehicle',
            'Ban',
            'BanEx',
            'CallLocalFunction',
            'CallRemoteFunction',
            'ChangeVehicleColor',
            'ChangeVehiclePaintjob',
            'ClearAnimations',
            'ConnectNPC',
            'Create3DTextLabel',
            'CreateExplosion',
            'CreateMenu',
            'CreateObject',
            'CreatePickup',
            'CreatePlayer3DTextLabel',
            'CreatePlayerObject',
            'CreateVehicle',
            'Db_close',
            'Db_free_result',
            'Db_get_field',
            'Db_num_fields',
            'Db_num_rows',
            'Db_open',
            'Db_query',
            'Delete3DTextLabel',
            'DeletePVar',
            'DeletePlayer3DTextLabel',
            'Deleteproperty',
            'DestroyMenu',
            'DestroyObject',
            'DestroyPickup',
            'DestroyPlayerObject',
            'DestroyVehicle',
            'DetachTrailerFromVehicle',
            'DisableInteriorEnterExits',
            'DisableMenu',
            'DisableMenuRow',
            'DisableNameTagLOS',
            'DisablePlayerCheckpoint',
            'DisablePlayerRaceCheckpoint',
            'EnableStuntBonusForAll',
            'EnableStuntBonusForPlayer',
            'EnableZoneNames',
            'Existproperty',
            'Fblockread',
            'Fblockwrite',
            'Fclose',
            'Fexist',
            'Fgetchar',
            'Flength',
            'Float',
            'Floatabs',
            'Floatadd',
            'Floatattan',
            'Floatcmp',
            'Floatcos',
            'Floatdiv',
            'Floatfract',
            'Floatlog',
            'Floatmul',
            'Floatpower',
            'Floatround',
            'Floatsin',
            'Floatsqroot',
            'Floatstr',
            'Floatsub',
            'Fmatch',
            'Fopen',
            'ForceClassSelection',
            'Format',
            'Fputchar',
            'Fread',
            'Fremove',
            'Fseek',
            'Ftemp',
            'Fwrite',
            'GameModeExit',
            'GameTextForAll',
            'GameTextForPlayer',
            'GangZoneCreate',
            'GangZoneDestroy',
            'GangZoneFlashForAll',
            'GangZoneFlashForPlayer',
            'GangZoneHideForAll',
            'GangZoneHideForPlayer',
            'GangZoneShowForAll',
            'GangZoneShowForPlayer',
            'GangZoneStopFlashForAll',
            'GangZoneStopFlashForPlayer',
            'GetMaxPlayers',
            'GetObjectPos',
            'GetObjectRot',
            'GetPVarFloat',
            'GetPVarInt',
            'GetPVarString',
            'GetPlayerAmmo',
            'GetPlayerArmour',
            'GetPlayerCameraFrontVector',
            'GetPlayerCameraPos',
            'GetPlayerCameraUpVector',
            'GetPlayerColor',
            'GetPlayerDrunkLevel',
            'GetPlayerFacingAngle',
            'GetPlayerFightingStyle',
            'GetPlayerHealth',
            'GetPlayerInterior',
            'GetPlayerIp',
            'GetPlayerKeys',
            'GetPlayerMenu',
            'GetPlayerMoney',
            'GetPlayerName',
            'GetPlayerObjectPos',
            'GetPlayerObjectRot',
            'GetPlayerPing',
            'GetPlayerPos',
            'GetPlayerScore',
            'GetPlayerSkin',
            'GetPlayerSpecialAction',
            'GetPlayerState',
            'GetPlayerSurfingVehicleID',
            'GetPlayerTeam',
            'GetPlayerTime',
            'GetPlayerVehicleID',
            'GetPlayerVehicleSeat',
            'GetPlayerVelocity',
            'GetPlayerVirtualWorld',
            'GetPlayerWantedLevel',
            'GetPlayerWeapon',
            'GetPlayerWeaponData',
            'GetPlayerWeaponState',
            'GetServerVarAsBool',
            'GetServerVarAsInt',
            'GetServerVarAsString',
            'GetTickCount',
            'GetVehicleComponentInSlot',
            'GetVehicleComponentType',
            'GetVehicleDamageStatus',
            'GetVehicleHealth',
            'GetVehicleModel',
            'GetVehiclePos',
            'GetVehicleTrailer',
            'GetVehicleVelocity',
            'GetVehicleVirtualWorld',
            'GetVehicleZAngle',
            'GetWeaponName',
            'Getdate',
            'Getproperty',
            'Gettime',
            'GivePlayerMoney',
            'GivePlayerWeapon',
            'HideMenuForPlayer',
            'IsPlayerAdmin',
            'IsPlayerConnected',
            'IsPlayerInAnyVehicle',
            'IsPlayerInCheckpoint',
            'IsPlayerInRaceCheckpoint',
            'IsPlayerInRangeOfPoint',
            'IsPlayerInVehicle',
            'IsPlayerNPC',
            'IsPlayerStreamedIn',
            'IsTrailerAttachedToVehicle',
            'IsValidObject',
            'IsValidPlayerObject',
            'IsVehicleStreamedIn',
            'Ispacked',
            'Kick',
            'KillTimer',
            'LimitGlobalChatRadius',
            'LimitPlayerMarkerRadius',
            'LinkVehicleToInterior',
            'Memcpy',
            'MoveObject',
            'MovePlayerObject',
            'NPC:OnNPCConnect',
            'NPC:OnNPCDisconnect',
            'NPC:OnNPCEnterVehicle',
            'NPC:OnNPCExitVehicle',
            'NPC:OnNPCModeExit',
            'NPC:OnNPCModeInit',
            'NPC:OnNPCSpawn',
            'NPC:PauseRecordingPlayback',
            'NPC:ResumeRecordingPlayback',
            'NPC:SendChat',
            'NPC:SendCommand',
            'NPC:StartRecordingPlayback',
            'NPC:StopRecordingPlayback',
            'PlayCrimeReportForPlayer',
            'PlayerPlaySound',
            'PlayerSpectatePlayer',
            'PlayerSpectateVehicle',
            'Print',
            'Printf',
            'PutPlayerInVehicle',
            'Random',
            'RemovePlayerFromVehicle',
            'RemovePlayerMapIcon',
            'RemoveVehicleComponent',
            'RepairVehicle',
            'ResetPlayerMoney',
            'ResetPlayerWeapons',
            'SendClientMessage',
            'SendClientMessageToAll',
            'SendDeathMessage',
            'SendPlayerMessageToAll',
            'SendPlayerMessageToPlayer',
            'SendRconCommand',
            'SetCameraBehindPlayer',
            'SetDeathDropAmount',
            'SetDisabledWeapons',
            'SetGameModeText',
            'SetGravity',
            'SetMenuColumnHeader',
            'SetNameTagDrawDistance',
            'SetObjectPos',
            'SetObjectRot',
            'SetPVarFloat',
            'SetPVarInt',
            'SetPVarString',
            'SetPlayerAmmo',
            'SetPlayerArmedWeapon',
            'SetPlayerArmour',
            'SetPlayerCameraLookAt',
            'SetPlayerCameraPos',
            'SetPlayerChatBubble',
            'SetPlayerCheckpoint',
            'SetPlayerColor',
            'SetPlayerDrunkLevel',
            'SetPlayerFacingAngle',
            'SetPlayerFightingStyle',
            'SetPlayerHealth',
            'SetPlayerInterior',
            'SetPlayerMapIcon',
            'SetPlayerMarkerForPlayer',
            'SetPlayerName',
            'SetPlayerObjectPos',
            'SetPlayerObjectRot',
            'SetPlayerPos',
            'SetPlayerPosFindZ',
            'SetPlayerRaceCheckpoint',
            'SetPlayerScore',
            'SetPlayerShopName',
            'SetPlayerSkillLevel',
            'SetPlayerSkin',
            'SetPlayerSpecialAction',
            'SetPlayerTeam',
            'SetPlayerTime',
            'SetPlayerVelocity',
            'SetPlayerVirtualWorld',
            'SetPlayerWantedLevel',
            'SetPlayerWeather',
            'SetPlayerWorldBounds',
            'SetSpawnInfo',
            'SetTeamCount',
            'SetTimer',
            'SetTimer',
            'SetTimerEx',
            'SetVehicleHealth',
            'SetVehicleNumberPlate',
            'SetVehicleParamsForPlayer',
            'SetVehiclePos',
            'SetVehicleToRespawn',
            'SetVehicleVelocity',
            'SetVehicleVirtualWorld',
            'SetVehicleZAngle',
            'SetWeather',
            'SetWorldTime',
            'Setproperty',
            'ShowMenuForPlayer',
            'ShowNameTags',
            'ShowPlayerDialog',
            'ShowPlayerMarkers',
            'ShowPlayerNameTagForPlayer',
            'SpawnPlayer',
            'StartRecordingPlayerData',
            'StopObject',
            'StopPlayerObject',
            'StopRecordingPlayerData',
            'Strcat',
            'Strcmp',
            'Strdel',
            'Strfind',
            'Strins',
            'Strlen',
            'Strmid',
            'Strpack',
            'Strunpack',
            'Strval',
            'TextDrawAlignment',
            'TextDrawBackgroundColor',
            'TextDrawBoxColor',
            'TextDrawColor',
            'TextDrawCreate',
            'TextDrawDestroy',
            'TextDrawFont',
            'TextDrawHideForAll',
            'TextDrawHideForPlayer',
            'TextDrawLetterSize',
            'TextDrawSetOutline',
            'TextDrawSetProportional',
            'TextDrawSetShadow',
            'TextDrawSetString',
            'TextDrawShowForAll',
            'TextDrawShowForPlayer',
            'TextDrawTextSize',
            'TextDrawUseBox',
            'Tickcount',
            'TogglePlayerClock',
            'TogglePlayerControllable',
            'TogglePlayerSpectating',
            'Update3DTextLabelText',
            'UpdatePlayer3DTextLabelText',
            'UpdateVehicleDamageStatus',
            'UsePlayerPedAnims',
            'Uudecode',
            'Uuencode',
            'Valstr'
            ),
        4 => array(
            'auto', 'char', 'const', 'double',  'float', 'int', 'long',
            'register', 'short', 'signed', 'static', 'string', 'struct',
            'typedef', 'union', 'unsigned', 'void', 'volatile', 'wchar_t'
            ),
            
        5 => array(
            'OnDialogResponse',
            'OnEnterExitModShop',
            'OnFilterScriptExit',
            'OnFilterScriptInit',
            'OnGameModeExit',
            'OnGameModeInit',
            'OnObjectMoved',
            'OnPlayerClickPlayer',
            'OnPlayerCommandText',
            'OnPlayerConnect',
            'OnPlayerDeath',
            'OnPlayerDisconnect',
            'OnPlayerEnterCheckpoint',
            'OnPlayerEnterRaceCheckpoint',
            'OnPlayerEnterVehicle',
            'OnPlayerExitVehicle',
            'OnPlayerExitedMenu',
            'OnPlayerInteriorChange',
            'OnPlayerKeyStateChange',
            'OnPlayerLeaveCheckpoint',
            'OnPlayerLeaveRaceCheckpoint',
            'OnPlayerObjectMoved',
            'OnPlayerPickUpPickup',
            'OnPlayerPrivmsg',
            'OnPlayerRequestClass',
            'OnPlayerRequestSpawn',
            'OnPlayerSelectedMenuRow',
            'OnPlayerSpawn',
            'OnPlayerStateChange',
            'OnPlayerStreamIn',
            'OnPlayerStreamOut',
            'OnPlayerTeamPrivmsg',
            'OnPlayerText',
            'OnPlayerUpdate',
            'OnRconCommand',
            'OnRconLoginAttempt',
            'OnVehicleDamageStatusUpdate',
            'OnVehicleDeath',
            'OnVehicleMod',
            'OnVehiclePaintjob',
            'OnVehicleRespray',
            'OnVehicleSpawn',
            'OnVehicleStreamIn',
            'OnVehicleStreamOut'
            )
            
        ),
    'SYMBOLS' => array(
        '(', ')', '{', '}', '[', ']', '=', '+', '-', '*', '/', '!', '%', '^', '&', ':'
        ),
    'CASE_SENSITIVE' => array(
        GESHI_COMMENTS => true,
        1 => false,
        2 => false,
        3 => false,
        4 => false,
        5 => false,
        ),
    'STYLES' => array(
        'KEYWORDS' => array(
            1 => 'color: #b1b100;',
            2 => 'color: #000000; font-weight: bold;',
            3 => 'color: #000066;',
            4 => 'color: #993333;',
            5 => 'color: #63648C;'
            ),
        'COMMENTS' => array(
            1 => 'color: #808080; font-style: italic;',
            2 => 'color: #339933;',
            'MULTI' => 'color: #808080; font-style: italic;'
            ),
        'ESCAPE_CHAR' => array(
            0 => 'color: #000099; font-weight: bold;'
            ),
        'BRACKETS' => array(
            0 => 'color: #66cc66;'
            ),
        'STRINGS' => array(
            0 => 'color: #ff0000;'
            ),
        'NUMBERS' => array(
            0 => 'color: #cc66cc;'
            ),
        'METHODS' => array(
            1 => 'color: #202020;',
            2 => 'color: #202020;'
            ),
        'SYMBOLS' => array(
            0 => 'color: #66cc66;'
            ),
        'REGEXPS' => array(
            ),
        'SCRIPT' => array(
            )
        ),
    'URLS' => array(
        1 => '',
        2 => '',
        3 => 'http://wiki.sa-mp.com/wiki/Function:{FNAME}',
        5 => 'http://wiki.sa-mp.com/wiki/Callback:{FNAME}',
        ),
    'OOLANG' => false,
    'OBJECT_SPLITTERS' => array(
        ),
    'REGEXPS' => array(
        ),
    'STRICT_MODE_APPLIES' => GESHI_NEVER,
    'SCRIPT_DELIMITERS' => array(
        ),
    'HIGHLIGHT_STRICT_BLOCK' => array(
        )
);


